# -*- coding: utf-8 -*-
"""Tugas1_Grafika Komputer_Latifah Nursya'banu_11180940000062.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tb37zACqdN0M6JEOXW1xKdtnHoNTLDHc
"""

#Algoriritma B
import matplotlib.pyplot as plt
plt.title('Bresenham Algorithm')
plt.xlabel('X Axis')
plt.ylabel('Y Axis')

def bres(x1,x2,y1,y2):
  x,y = x1,y1
  dx = abs(x2-x1)
  dy = abs(y2-y1)
  m = dy/float(dx)

  if m>1:
    dx,dy = dy,dx 
    x,y = y,x
    x1,y1 = y1,x1
    x2,y2 = y2,x2

  p=2*(dy-dx)
  print('x = ,y = ',(x,y))

  xcoordinate = [x]
  ycoordinate = [y]

  for k in range(2,dx):
    if p>0:
      y = y+1 if y<y2 else y-1
      p = p+2*(dy-dx)
    else:
      p = p+2*dy
    
    x = x+1 if x<x2 else x-1

    print('x = ,y = ',(x,y))
    xcoordinate.append(x)
    ycoordinate.append(y)
  
  plt.plot(xcoordinate,ycoordinate)
  plt.show()

def main():
  x1 = int(input('Enter the starting point of x : '))
  y1 = int(input('Enter the starting point of y : '))
  x2 = int(input('Enter the end point of x : '))
  y2 = int(input('Enter the end point of y : '))

  bres(x1,x2,y1,y2)

if __name__ == '__main__':
  main()

#Algoritma A
import matplotlib.pyplot as plt
print('Enter the starting point of x : ')
x1 = int(input())
print('Enter the starting point of y : ')
y1 = int(input())
print('Enter the end point of x : ')
x2 = int(input())
print('Enter the end point of y : ')
y2 = int(input())

dx = x2-x1
dy = y2-y1

if abs(dx)>abs(dy):
  steps = abs(dx)
else:
  steps = abs(dy)

xinc = dx/steps
yinc = dy/steps

i = 0
xcoordinate =[]
ycoordinate =[]

while i<steps:
  i+=1
  x1 = x1+xinc
  y1 = y1+yinc
  print('x1 = ,y1 = ',(x1,y1))
  xcoordinate.append(x1)
  ycoordinate.append(y1) 

plt.plot(xcoordinate,ycoordinate)
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.title('DDA Algorithm')
plt.show()